### ISSUE TITLE
Please add Proxy Settings in the APP

### ISSUE THREAD

**Issue by 3rain3ug** [Aluxian/WhatsApp-Desktop#10]
Please add Proxy Settings in the APP

**Comment by rodrigogs** [comment]
Agreed

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

This feature is being tracked here now: https://github.com/Aluxian/Whatsie/issues/33
