### ISSUE TITLE
How to scan with WhatsApp on iPhone ?

### ISSUE THREAD

**Issue by herve1976** [Aluxian/WhatsApp-Desktop#11]

**Comment by Aluxian** [comment]
WhatsApp for Desktop is not compatible with iOS due to a limitation of the operating system. The web app (thus, my app) works through the mobile app, and the mobile app must be able to communicate with the web app in the background, which iOS won't let it do.

**Comment by pchaganti** [comment]
Thats too bad. Hopefully iOS will add this soon.

**Comment by bcalik** [comment]
@herve1976 @pchaganti the option is actually available but its hidden. Hidden option can be enabled with a jailbreaked iphone.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
