### ISSUE TITLE
windows version, icon on top left is default

### ISSUE THREAD

**Issue by Firex2** [Aluxian/WhatsApp-Desktop#12]
there is no icon / default icon on the window top left, its only cosmetic

![wa](https://cloud.githubusercontent.com/assets/2738065/8288265/45a0d034-1915-11e5-9fa7-bb9272bac197.PNG)

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
