### ISSUE TITLE
Uninstall Shortcut

### ISSUE THREAD

**Issue by Stanzilla** [Aluxian/WhatsApp-Desktop#16]
Your installer puts an uninstaller shortcut into 
`C:\ProgramData\Microsoft\Windows\Start Menu\Programs`

only app launchers belong there, not uninstaller launchers. If you want to have them both there, people usually make a folder, i.e. have a WhatsApp for Windows folder and have both launcher and uninstaller launcher in there.

**Comment by Aluxian** [comment]
Thanks for the heads up.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
