### ISSUE TITLE
Rewrite using Electron

### ISSUE THREAD

**Issue by steelbrain** [Aluxian/WhatsApp-Desktop#21]
https://github.com/atom/electron <-- Electron
It's the same thing except that you'll have to change your JS in a few places.
It'll also let you set a tray icon and preferences on right click context menu in all platforms.

**Comment by bcalik** [comment]
@steelbrain Here I made it. https://github.com/bcalik/Whatsapp-Desktop

**Comment by gutierri** [comment]
:+1:

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Completely rewritten for Electron, with lots of features and improvements.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
