### ISSUE TITLE
Please add link in About dialog

### ISSUE THREAD

**Issue by dserodio** [Aluxian/WhatsApp-Desktop#22]
Please add a link to the GitHub repo or the app's website in the About dialog.

**Comment by Aluxian** [comment]
I will.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
