### ISSUE TITLE
Window blur event is not firing when hiding app

### ISSUE THREAD

**Issue by bcalik** [Aluxian/WhatsApp-Desktop#23]
Hello,

This might my actually Nwjs's issue, but anyway I would like to report here.
Basicly, the window blur event is not firing when you hide the app window.

So it keeps you "Online" all the time, and also the last conversation keeps running, so that it does not send notifications from last conversation, and marks the messages as read.

I actually tried to make the same Whatsapp Desktop app a month ago, but stuck with the same issue and gived up. Today I saw Aluxian's repo and the same issue is also here.

Possible solution may be calling the related blur operation inside the app manually.

Thanks.

**Comment by bcalik** [comment]
I recently done some testing with Electron instead of NW.js.
It solves the problem and also other minor issues.
https://github.com/atom/electron
You can rewrite the app with Electron to solve this problem.

**Comment by Aluxian** [comment]
I will look into it. Probably I'm going to switch to Electron, it seems better and more polished.

**Comment by bcalik** [comment]
@Aluxian: Here I made it: https://github.com/bcalik/Whatsapp-Desktop
Feel free to fork or copy.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
