### ISSUE TITLE
App does not respect ClearType (I guess) > hard to read text

### ISSUE THREAD

**Issue by ksya** [Aluxian/WhatsApp-Desktop#24]
See the following picture for the difference:

![whatsappcleartype](https://cloud.githubusercontent.com/assets/3142911/8316519/f37d5f82-19f7-11e5-91d3-48bb0bfa1ac0.png)

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
