### ISSUE TITLE
Arch linux package

### ISSUE THREAD

**Issue by sanderboom** [Aluxian/WhatsApp-Desktop#25]
Can be found here: https://aur4.archlinux.org/packages/whatsapp-desktop/

Keep up the good work.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

Whatsie has its own linux repositories :smile:
