### ISSUE TITLE
Add RPMs for Fedora  openSUSE Mandriva and derivates

### ISSUE THREAD

**Issue by sergioad** [Aluxian/WhatsApp-Desktop#26]
Hello, could you add WhatsApp for desktop RPMs for Fedora openSUSE Mandriva and their derivates?

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

It has support for RPM-based distros.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
