### ISSUE TITLE
Don't show up in Cairo/GLX Dock 

### ISSUE THREAD

**Issue by e-M-c-E** [Aluxian/WhatsApp-Desktop#27]
App don't create launcher in Cairo/GLX Dock. When launcher is created by hand, the app don't "respect" them. I mean.. After launcher is created manually and app is open, just don't show up in Cairo.
System: Linux Mint 17.2 RC x64
Cairo: 3.4.0
App version: 1.1.0

![zrzut_ekranu](https://cloud.githubusercontent.com/assets/13028529/8323801/73a0ab1e-1a49-11e5-9f5c-7f8173e9a102.png)

**Comment by e-M-c-E** [comment]
Update: On Mint 17.3 this issue stil presist.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
