### ISSUE TITLE
Improve notificacion design

### ISSUE THREAD

**Issue by Flash-back** [Aluxian/WhatsApp-Desktop#28]
Notification design is very poor. Please improve it to make something like Telegram Desktop notifications.

Greetings and congratulations for the work.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
