### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by Aluxian** [Aluxian/WhatsApp-Desktop#3]
https://userstyles.org/styles/browse/whatsapp

**Comment by Aluxian** [comment]
Assigned to @g19-hs, @franciscoib and @harjeetlalh

**Comment by g19-hs** [comment]
Alright, will start working on it soon.

**Comment by g19-hs** [comment]
Please checkout the following pull request: 
https://github.com/Aluxian/WhatsApp-Desktop/pull/76

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
