### ISSUE TITLE
Pressing ESC button close the application

### ISSUE THREAD

**Issue by streambinder** [Aluxian/WhatsApp-Desktop#30]
Don't know if it's an expected behavior, but don't think it's useful anyway.

**Comment by Aluxian** [comment]
Somebody requested it before, and it was a minor thing to add. What platform are you on? I'm thinking I should probably only enable it for Windows.

**Comment by streambinder** [comment]
Linux Fedora 22.

**Comment by Ishmaeel** [comment]
I too think this feature does not make much sense - even on Windows. I'm trained to dismiss image/media popups with ESC key and having it close the whole window is kinda jarring.

Make it optional perhaps?

**Comment by MartijnDevNull** [comment]
Would like to see this to, highly annoying

**Comment by MartijnDevNull** [comment]
I'm on Debian btw, I don't think this should be a platform specific option

**Comment by hashworks** [comment]
Yeah +1, this annoys me as well. I'm always pressing ESC when I want to close a picture popup.

**Comment by rodgerpaulo** [comment]
+1 every time i'm hit ESC expecting to close

**Comment by vukasin0** [comment]
Hate this too - plz remove it. ESC should only closing popups inside app but not APP.

**Comment by gtataranni** [comment]
+1 I'm on Mint and also affects me. Every time I want to close a picture preview and I press ESC I close the application instead

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
