### ISSUE TITLE
build:platform produces unusable app

### ISSUE THREAD

**Issue by saxonbeta** [Aluxian/WhatsApp-Desktop#32]
I am trying to compile in Arch Linux using the tasks build:linux32 or build:linux64 but the produced app is useless, because when it is executed only shows a empty window.
But if I use the task pack:platform:deb I get a working app.

**Comment by saxonbeta** [comment]
Never mind, I have found the problem, closing.

**Comment by nephilim1973** [comment]
Please, could you post your solution here ?
