### ISSUE TITLE
Blurred fonts in Windows 8.1

### ISSUE THREAD

**Issue by migue74** [Aluxian/WhatsApp-Desktop#33]
Hello, the font is very blurry compared to web.whatsapp.com in browsers. I tried to build with "--disable-direct-write" in chromium-args but the result is almost the same. Is it possible to fix it? Thanks!

**Comment by korayarikan** [comment]
I have the same issue on Chrome + Windows 8.1. All the other browser tabs/windows look very sharp, only Whatsapp Web seems to have the problem.

![image](https://cloud.githubusercontent.com/assets/15609999/10880467/1005eb46-8164-11e5-9e15-ee7acbaebf3e.png)

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
