### ISSUE TITLE
GNOME 3 Indicator

### ISSUE THREAD

**Issue by boesing** [Aluxian/WhatsApp-Desktop#34]
I've got a suggestion for a new feature/app which would provide an Indicator in the Top-Bar with unread message count, e.g.

There is already an extension for Skype:
https://extensions.gnome.org/extension/696/skype-integration/

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

This feature is being tracked here: https://github.com/Aluxian/Whatsie/issues/34
