### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by meshoo12** [Aluxian/WhatsApp-Desktop#35]
http://whatsapp-desktop.com
The website is down !

**Comment by Aluxian** [comment]
WhatsApp contacted me and I don't own the domain anymore. I'm working on a new
app, with a different name, logo and domain. Stay tuned!

--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com


On Sun, Jun 28, 2015 at 7:30 am, meshoo12 < notifications@github.com [notifications@github.com] > wrote:
http://whatsapp-desktop.com [http://whatsapp-desktop.com]
The website is down !

**Comment by xoneco** [comment]
Is there a way to download the built client while the website is down?

**Comment by Aluxian** [comment]
Yes! You can still get it from the releases page github.com/Aluxian/WhatsApp-Desktop/releases

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
