### ISSUE TITLE
Mass Group Add and Limit

### ISSUE THREAD

**Issue by leannecrow** [Aluxian/WhatsApp-Desktop#36]
Is it possible to mass add users from my phone list and increase the group size by 200?

**Comment by Aluxian** [comment]
You should try doing this on your phone.


--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On Sun, Jun 28, 2015 at 8:36 am, leannecrow < notifications@github.com [notifications@github.com] > wrote:
Is it possible to mass add users from my phone list and increase the group size
by 200?

**Comment by leannecrow** [comment]
I will but the default Whatsapp client does not have this feature.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

Whatsie is just a wrapper for WhatsApp Web, so you should first try to find a solution for WhatsApp Web.
