### ISSUE TITLE
Window Position in OS X

### ISSUE THREAD

**Issue by rotvulpix** [Aluxian/WhatsApp-Desktop#38]
When you use the app in a macbook who has multiple displays the app hides itself when you unplug the external displays without ability to find it.

**Comment by rotvulpix** [comment]
Temporal solution using AppleScript editor

```
tell application "System Events" to tell window 1 of process "UnofficialWhatsApp"
	set position to {100, 100}
end tell
```

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
