### ISSUE TITLE
Copy text from contact info page

### ISSUE THREAD

**Issue by orschiro** [Aluxian/WhatsApp-Desktop#40]
Hi @Aluxian,

Great work on this WhatsApp client, thank you!

I have one request. I tried to copy a phone number from the Contact info page of a contact. However, I am not able to select the text. 

Can this text be made selectable?

Thankfully,

Robert

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Comment by orschiro** [comment]
Thanks for that, @Aluxian!

I will give it a try. :-)

~Robert
