### ISSUE TITLE
Recreates shortcut in start menu on Windows 8.1

### ISSUE THREAD

**Issue by francwalter** [Aluxian/WhatsApp-Desktop#41]
Hello
Often I need to delete the shortcut in the Windows Start Menu (only the user's start-menu, not the All User start menu) because WhatsApp-Desktop recreates it automatically.

This is the Link: "C:\Program Files (x86)\Unofficial WhatsApp for Desktop\UnofficialWhatsApp.exe"
This is the entry: "C:\Users\f\AppData\Roaming\Microsoft\Windows\Start Menu\Programs"

I can reproduce it easily when I press the Reload menu item, then a new entry in the user's start-menu is created.
I use as a kind of Windows 7 style start menu in Windows 8.1 a symbol bar with the above path as it can be instructed in the net (Windows 8 has initial no real Start-Menu).

"Check for Update on Launch" and "Launch on startup" is not activated and I am running 1.1.0 on Windows 8.1 Professional 64-Bit.
Not a big issue, but a bit annoying.
Thanks
frank

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Comment by francwalter** [comment]
Did you fix this bug (in Whatsapp-Desktop), or why did you close this issue?

**Comment by Aluxian** [comment]
I did not fix this in WhatsApp-Desktop. Also, if I remember correctly, I think Windows 7 and Windows 8  (but not Windows 10) require a shortcut in the Start Menu for apps to be able to create notifications, that's why the WhatsApp-Desktop re-created it every time.

**Comment by francwalter** [comment]
This is the first timeI hear this. Have you any proof for this or is this a hypothesis?

**Comment by Aluxian** [comment]
3rd bullet here: https://github.com/nwjs/nw.js/wiki/Notification#toast-notification-requires-node-webkit--v011
