### ISSUE TITLE
We recommend using WhatsApp Web with one of the following browsers:

### ISSUE THREAD

**Issue by mpnegro** [Aluxian/WhatsApp-Desktop#42]
From Today, Whats app is asking to use one off the browsers and don't let the app continue to be used

**Comment by Aluxian** [comment]
I'm checking this out right now.

**Comment by Aluxian** [comment]
It works for me. What OS are you using?

**Comment by mpnegro** [comment]
In Ubuntu 14.04 gives that message. In Ubuntu 15.04 it works

**Comment by mpnegro** [comment]
In 14.04, even if i terminate all sessions it continue showing the browse selection

**Comment by Aluxian** [comment]
I don't know why that would happen. I wonder if anyone else is experiencing this.

**Comment by Nicklog90** [comment]
It doesn't work anymore for me. Im using Windows 10.

**Comment by shulhi** [comment]
It happens to me too. I'm on OSX Yosemite, I have to clear the whatsapp folder in `~/Library/ApplicationSupport`, but then I have to re-authenticate the client to my phone again.

**Comment by mpnegro** [comment]
have you remove all data or the cache?

**Comment by Nicklog90** [comment]
after clearing the cache it works again.

**Comment by mpnegro** [comment]
In Linux (ubuntu 14.04) do to /home/(yourhome)/.config/UnofficialWhatsApp an delete 
Application Cache
And Cache
And it starts working

**Comment by Kurobyte** [comment]
Yep, deleting the cache worked for me in Win 7 (x64)

**Comment by matzex** [comment]
I had the same problem on Ubuntu 15.04 64bit. Deleting the cache folders (mpnegro  https://github.com/Aluxian/WhatsApp-Desktop/issues/42#issuecomment-124045042 ) worked for me.

**Comment by shulhi** [comment]
Does the problem happen again after you exit the application? I have to clear the cache every time I closed the application. I'm on OSX (Yosemite).

**Comment by matzex** [comment]
Same for me under Ubuntu 15.04 64bit. It's a little bit annoying to clean up the cache every time I want to start the application.

**Comment by pstarace** [comment]
I confirm. Deleting the cache works for the first run but you need to do it again every time the application start.

**Comment by CandyPanda** [comment]
The deleting Cache Method is working (Win 8,1 Pro x64)

**Comment by Aluxian** [comment]
Hey guys, I’m sorry for not being active into this, it’s because I’m really busy with another project for the next 2 weeks. After I finish with it I’ll have time to fix more issues and improve the app.

I’m really glad you found a way to fix it, I’m directing people to this issue. 

	Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com

On 24 Jul 2015 at 00:05:45, Marcel Kuhla (notifications@github.com) wrote:

The deleting Cache Method is working (Win 8,1 Pro x64)

**Comment by YNedderhoff** [comment]
Delete Cache is working (Ubuntu 15.04). Rather annoying having to to it every time, though.

**Comment by elidealista** [comment]
Using it on MAC OSX (Yosemite) Not a good thing having to clear the cache everytime we use the app. Too bad because I really liked this "unofficial whatsapp app"

**Comment by omperus** [comment]
Can someone explain how to make this work for Windows 8? i already cleared IE cache and used ccleaner for everything else, message still shows up.

**Comment by FollowCandyPanda** [comment]
You need to clear the Cache of the Whatsapp Application.

You will find it under -> Users -> Your Name -> Appdata -> Local -> Unofficial Whatsapp -> Application Cache -> Delete everything inside

**Comment by Kurobyte** [comment]
@omperus you should clear the cache of the APP not the cache of the IE.
Delete it manualy in `C:\Users\{YOURUSER}\AppData\Local\UnofficialWhatsApp\Application Cache`

**Comment by omperus** [comment]
Thanks, its working now.

**Comment by elidealista** [comment]
Using Mac OSX... clearing the cache worked but I have to do this everytime I want to use the app! so it is not an ideal solution actually

**Comment by FollowCandyPanda** [comment]
Could someone write a little workaround for this issue?

It's 01:21 AM at Germany and me brain doesn't work decently anymore...

**Comment by Aluxian** [comment]
I think forcing a user agent that looks like Chrome should fix it. There's ` user-agent ` that can be set in the manifest
https://github.com/nwjs/nw.js/wiki/manifest-format

--

Alexandru Rosianu
Web & Android Developer
aluxian.com | startersquad.com On Sat, Jul 25, 2015 at 2:24 am, Marcel Kuhla < notifications@github.com [notifications@github.com] > wrote:
Could someone write a little workaround for this issue?

It's 01:21 AM at Germany and me brain doesn't work decently anymore...

—
Reply to this email directly or view it on GitHub
[https://github.com/Aluxian/WhatsApp-Desktop/issues/42#issuecomment-124764217] .[https://github.com/notifications/beacon/ABWmdsWzCIzgx2ScDerfbgtqZj9k6C0Dks5ogsCSgaJpZM4FeQD1.gif]

**Comment by Guylub** [comment]
In Windows 7, this will help: In the folder C:\Users\Your Name\AppData\Local\UnofficialWhatsApp\Application Cache\Cache to delete all files. Then right-click on the folder and select Cache properties. In the properties tab, select Security, then select your name and click on the edit button again to choose your name and permissions for your name tick with full control DENY. Then confirm by clicking OK. Now even you yourself do not have access to the Cache folder or the program itself. The program will not be able to write to the folder, or read it. And you no longer have to erase the contents of each folder before restarting the program. It will probably work on other operating systems. If anyone knows how to disable access to the folder in other systems, let's here to give to others. This is a temporary solution until the author repair program and will release a new version that will not suffer from the said ailment.

**Comment by olbapnauj** [comment]
howdy 
For those users on mac having problems you can use this version until Aluxian release an update.
https://github.com/bcalik/Whatsapp-Desktop/releases
Unofficial whatsapp web desktop client for OSX. Build with Electron is the @bcalik clone of this app. 

is more energy friendly and the cpu doesn't  stress  also the app is updated so no unsupported error.
it clears "~/Library/ApplicationSupport/Application Cache/Index" file automaticly. Not the entire ApplicationSupport folder so it also keeps you logged-in.

regards.

@elidealista @shulhi

**Comment by Isuru-Nanayakkara** [comment]
How do I clear the cache in Mac OS X?

**Comment by aerobrain** [comment]
I experiencing same issue today. I'm using Windows 7 64bit. Problem solved after deleting the cache as per instruction above. Thank you!

**Comment by jackfido** [comment]
I have the same problem, my SO: Ubuntu 64 bits, it solve (temporal) cleaning the cache too.

**Comment by sebastiande** [comment]
I fixed it, if you want to include it in the repo:

You need the rimraf node module installed, as I think its the best solution to delete complete directories (should work on windows an mac too, only tested on linux)

app.js :
Add following after "var gui = require('nw.gui');"
```javascript
var rmdir = require('rimraf');
```

Add following at the end of the file:
```Javascript
// cleanup cache
win.on('close', function() {
  var dataPath = gui.App.dataPath;
  rmdir(dataPath + "/Cache", function(error){ console.log(error); });
  rmdir(dataPath + "/Application Cache", function(error){ console.log(error); });
  this.close(true);
});
```

You should also include the "rimraf": "2.1" in the devDependencies (package.json)

**Comment by dserodio** [comment]
@Isuru-Nanayakkara `rm -rf ~/Library/Application\ Support/UnofficialWhatsApp/`

**Comment by Isuru-Nanayakkara** [comment]
@dserodio Thank you :+1:

**Comment by dhamaniasad** [comment]
:+1:  Same thing happens to me on OS X. Doing `rm -rf ~/Library/Application\ Support/UnofficialWhatsApp/` solves the issue, but it requires scanning the barcode again, which is annoying.

**Comment by bcalik** [comment]
@dhamaniasad Try this alternative which doesn't have any issue. You won't need to rescan barcode https://github.com/bcalik/Whatsapp-Desktop

**Comment by dhamaniasad** [comment]
@bcalik Thanks, it seems to be working fine atm.

**Comment by orschiro** [comment]
@bcalik 

Is it possible to provide a `deb` package? :)

**Comment by shulhi** [comment]
@dhamaniasad do this instead `rm -rf ~/Library/Application\ Support/UnofficialWhatsApp/Application\ Cache/Index`, you don't have to rescan the barcode.

**Comment by pipaman** [comment]
I've experienced the same issue in Windows and it was fixed cleaning the cache. Thank you!

**Comment by francwalter** [comment]
Yes, the solution from Guylub (9 days ago) helped.
I deny permission to:
c:\Users\myusername\AppData\Local\UnofficialWhatsApp\Application Cache\Cache\
and it starts again without this error.
I hope someone (or the author) fixes this (and other) bug(s) :)
Still very useful this application, better than the browsers WA-tab, I consider.
Thank's
frank

**Comment by Coelen** [comment]
Installed the Bcalik's release (https://github.com/bcalik/Whatsapp-Desktop/releases), seems to work fine :+1:

**Comment by francwalter** [comment]
Thank for this way, changed as well now on Mac. And this WA-project seems not abandoned.
What is the big difference?

**Comment by Coelen** [comment]
The original WhatsApp logo, so wait some time until WA will request to use something else. Notifications seem to work, so I think not a big change.

**Comment by Coelen** [comment]
Original WA icon (Although they probably will request a pull down when they discover this). No need for resetting anything, works out of the box. Notifications seem to work fine.

**Comment by francwalter** [comment]
Indeed, the Icon is the origin!
I dont care about that, but it not harms :)
What I care is that it works, so I will stick to it as long as it works

This project seems already nearly abandoned, unfortunately. Started nice, but has some bugs in Windows version.

**Comment by simonbcn** [comment]
The Bcalik's release doesn't work well in Linux: it opens a borderless window and it doesn't show any icon in Unity launcher (Ubuntu 14.04).

**Comment by orschiro** [comment]
@simonbcn 

Thanks for reporting this back. I didn't test it because it does not provide an installable binary. Does anyone know how we can fix the issue here in this version to remain having a solid Linux client?

**Comment by bcalik** [comment]
@simonbcn There isn't any linux version of my release. If you compiled it yourself, then send me some screenshots and tell me your requests, so I can see what's going on, and fix it. Please [create an issue](https://github.com/bcalik/Whatsapp-Desktop/issues) with screenshots. I am not a linux user so there is no way I can see the issues. Thanks.

**Comment by natsu90** [comment]
thanks @shulhi it work

**Comment by hhklmc** [comment]
For Mac users,
Go to Automator > Create New Workflow

Insert shell code below:
rm -rf ~/Library/Application\ Support/UnofficialWhatsApp/Application\ Cache/Index
open /Applications/UnofficialWhatsApp.app/

save as Application. Name it "Whatsapp Launcher".

**Comment by shulhi** [comment]
@hhklmc You don't have to do that at all. Just remove write access to `Index` and it will works even after quitting.

**Comment by hhklmc** [comment]
@shulhi Thank you for your suggestion. It did work for the first time I ran the app but then stopped working after restarting the OS. I might be doing something wrong though.

**Comment by orschiro** [comment]
@gonzalocasal 

Thanks! Is this a permanent workaround or do you need to apply it each time you start the program?

**Comment by gonzalocasal** [comment]
@orschiro 

permanent!

**Comment by orschiro** [comment]
@gonzalocasal 

Nice, thanks!

**Comment by YNedderhoff** [comment]
Awesome, thanks!

**Comment by ericoporto** [comment]
Thank you @gonzalocasal

**Comment by pheraph** [comment]
@gonzalocasal Thanks, did the trick also on OSX for me.

**Comment by peterrus** [comment]
Fix also works for me

**Comment by hhklmc** [comment]
@gonzalocasal's solution works for me on OSX Yosemite.

rm ~/Library/Application\ Support/UnofficialWhatsApp/Application\ Cache/Index
sudo chmod 000 ~/Library/Application\ Support/UnofficialWhatsApp/Application\ Cache/

**Comment by iniaski** [comment]
@gonzalocasal  Muchas gracias, por ahora funciona el cambio de permisos correctamente.

**Comment by sadalavoaoj** [comment]
The workaround removing permissions caused another error.
The icon now is duplicated. I guess we will have to wait for the new version.


Cheers.

**Comment by MykeLWulf** [comment]
So I managed to get it working in Windows by marking the index file as "Read Only".
I'm mostly posting this here for Windows users since everything posted with specific instructions were for Mac OS or Ubuntu/Linux. :)

Pretty simple and straightforward, navigate to C:\Users\[current user]\AppData\Local\UnofficialWhatsApp\Application Cache\Cache and right click on the file titled index. Check the "Read Only" box and save it.

**Comment by VansonLeung** [comment]
@hhklmc worked

**Comment by MaxMoreno** [comment]
Delete file in 
/home/max/.config/UnofficialWhatsApp/Application Cache/Cache/

luky!

**Comment by Kevinsillo** [comment]
I create in Startup a .bat with next:

rd /S /Q "%USERPROFILE%\AppData\Local\UnofficialWhatsApp\Application Cache\Cache"

**Comment by s1h4d0w** [comment]
**Writing here to add information to this ticket:**

I've been using the Unofficial Whatsapp Desktop Client for about a week now on Windows 10 Home 64bit and it always worked great. I've used it every single day without problem (Monday through Thursday). Suddenly this morning it gave me the browser error and I renamed the Application Cache and Cache folder to fix the problem (it did not require me to rescan the QR code).

**Comment by marty90** [comment]
@gonzalocasal 
Worked for me: Ubuntu 14.04 64 bit

**Comment by inaveedahmed** [comment]
@gonzalocasal Thanks!

**Comment by kname** [comment]
kubuntu 15.10 64-bit
dell inspiron 17r

1.when searching around online there is a .deb file for software center
2. in my case renaming or denying both read and write access to folder /.config/UnofficialWhatsApp/Application Cache/  was not good enough since app recreated folder afresh every time i opened it so what i hd to do was to just deny writeing access and allow read only. that worked perfectly. Thanks-you very much for the help :) very comfy app

**Comment by JorgeAT227** [comment]
ubuntu 15.10 64-bit
alienware 15 

delete index and then "protect" app cache directory works just fine 

Gracias @gonzalocasal
Thanks @gonzalocasal

**Comment by Aluxian** [comment]
Hey, everyone, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

I've fixed this problem in Whatsie by cleaning the user agent.

**Comment by s1h4d0w** [comment]
Ah, Whatsie is unavailable too. I've been using Franz for a while now, great app that offers similar (and more) functionality!
