### ISSUE TITLE
Dark/black Theme ?

### ISSUE THREAD

**Issue by alduccino** [Aluxian/WhatsApp-Desktop#45]
Hi, 
I was wondering if you plan to add a black/dark theme like you did for your Messenger app ?

**Comment by Aluxian** [comment]
Yes, that's planned.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

It has 5+ themes :)
