### ISSUE TITLE
deprecated node-webkit-builder

### ISSUE THREAD

**Issue by simonbcn** [Aluxian/WhatsApp-Desktop#47]
When I install the dependencies, it shows this warning:
```
npm WARN deprecated node-webkit-builder@1.0.13: WARNING: This module has been renamed to nw-builder. Install using nw-builder instead, node-webkit-builder will no longer be updated.
```

**Comment by rickvdl** [comment]
Same here, ignored it and built the app, it starts but don't see anything on the screen.

**Comment by Aluxian** [comment]
Well, WhatsApp for Desktop is deprecated too. Please switch to Whatsie:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
