### ISSUE TITLE
Turkish translation

### ISSUE THREAD

**Issue by muratbiskin** [Aluxian/WhatsApp-Desktop#5]
Hello
I loved WhatsApp for Desktop and I would like to translate into Turkish.

**Comment by Aluxian** [comment]
Hey @muratbiskin, WhatsApp for Desktop is a wrapper for web.whatsapp.com. I'm not sure whether WhatsApp Web already has translations, but even if it didn't, I wouldn't be able to add them.

Anyway, thanks for the kind intention.
