### ISSUE TITLE
Tray icon and ability to minimize

### ISSUE THREAD

**Issue by rbieb** [Aluxian/WhatsApp-Desktop#50]
Would be awesome to get a tray icon and the ability to start to program minimized and to minimize it on closing the program.

**Comment by SoumenDass** [comment]
Please add this feature for the Linux version as well. I'm using Linuxmint with Cinnamon DE.

**Comment by leoheck** [comment]
Please, I want this for Ubuntu too. I can give you some help to do that if you need!

**Comment by e-M-c-E** [comment]
Yeap.. This would be great! I am a Mint 17.3 Mate user and on my system tray icon don't shows up.

**Comment by dbogdanov** [comment]
Definitely, would be very useful to have a tray icon. Otherwise, this app does not declutter much the workflow, I could as easily have a tab open in my browser.

**Comment by dbogdanov** [comment]
Currently, this app is unusable on Linux for me due to this issue. 

Similar issue for Facebook Messenger [was solved](https://github.com/Aluxian/Facebook-Messenger-Desktop/issues/312) in a fork. It would be nice incorporate that back into the original and here.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
