### ISSUE TITLE
Not loading at all

### ISSUE THREAD

**Issue by shulhi** [Aluxian/WhatsApp-Desktop#51]
Anyone had the same problem?
<img width="793" alt="screen shot 2015-08-27 at 9 37 40 am" src="https://cloud.githubusercontent.com/assets/913103/9510532/4d825dd2-4c9f-11e5-83e9-e6cec1e87c35.png">

**Comment by gutierri** [comment]
https://web.whatsapp.com/ -> Not Working :-1:

**Comment by shulhi** [comment]
@gutierri did you receive `timed out to start connect` error? It works fine for my friends. We are in the same subnet.

**Comment by gutierri** [comment]
@shulhi Yes!

Now is working normally! :+1:

**Comment by shulhi** [comment]
@gutierri It's working fine now. I'm closing the issue.
