### ISSUE TITLE
OSX Notification

### ISSUE THREAD

**Issue by Jianlucah** [Aluxian/WhatsApp-Desktop#54]
Hi, when message arrived on my Whatsapp Account, Whatsapp-Desktop doesn't show the notification (it's work only badge icons): it's normal or not?

Thanks!

**Comment by stefan-r** [comment]
Hi Jianlucah, I just installed the app on osx and it works fine (as long as the app is in background).

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
