### ISSUE TITLE
Feature-Request: Insert Smileys via shortcut

### ISSUE THREAD

**Issue by stefan-r** [Aluxian/WhatsApp-Desktop#56]
First I want to say thank you for this wonderful tool. I highly appreciate to use my computer keyboard to write messages faster than ever. I also don't like to have many open tabs in my browser and love using this stand alone application sind I installed it.

One little thing I was not able to figure out (if this feature is already implemented): How can I quickly insert smileys? I would expect that character sequences like `;)`, `:-D` etc. are transformed into their emoticon equivalents. At least, it would be okay to type sth. like `:blink:` as it is possible in Slack.

Would you say this feature can be implemented or is this something only the web client itself is able to provide?

Thank you once again and best regards,
Stefan

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

I haven't added this feature in Whatsie yet, but it's being tracked here: https://github.com/Aluxian/Whatsie/issues/32
