### ISSUE TITLE
Feature-Request: Integrate notifications with notification panel on Windows 10.

### ISSUE THREAD

**Issue by jesusfj710** [Aluxian/WhatsApp-Desktop#57]
The notifications on the last version only use an emergent pop-up. Don't keep on notification panel on Windows 10. Please, integrate it on this panel. That will be great.
Sorry my bad english.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
