### ISSUE TITLE
Control font family and size?

### ISSUE THREAD

**Issue by mmoayyed** [Aluxian/WhatsApp-Desktop#58]
Thank you for the great app!

Is possible to somehow control the font name and size? Could this be considered a feature request?

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

This feature has not been added yet, but it's being tracked here: https://github.com/Aluxian/Whatsie/issues/23

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
