### ISSUE TITLE
Any way to get this working on iOS?

### ISSUE THREAD

**Issue by koolnez** [Aluxian/WhatsApp-Desktop#59]
First of all, a big thank you for this fantastic piece of ingenuity.

Now if only this could work on my iPad ... that would make me delirious with pleasure! LOL

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

It doesn't have any special support for iPads, but I've seen WhatsApp Web apps in the App Store, for iPads. Try one of those.
