### ISSUE TITLE
ios ? 

### ISSUE THREAD

**Issue by syrakozz** [Aluxian/WhatsApp-Desktop#6]
its not working with ios

**Comment by jandetlefsen** [comment]
It's a limitation by iOS afaik. Won't work.

**Comment by Aluxian** [comment]
Yep, it's not compatible with iOS due to a limitation of the operating system. The web app (thus, my app) works through the mobile app. The mobile app must be able to communicate with the web app in the background, which iOS won't let it do.

**Comment by saada** [comment]
I felt a glimpse of hope for a second, but then I realized it's just a UI on top of the existing platform. Nice work still...

**Comment by Aluxian** [comment]
Hehe, sorry to disappoint. I'm sure WhatsApp is working on it though, so don't lose hope ;)
