### ISSUE TITLE
[Bug] Client is flagged as unsupported

### ISSUE THREAD

**Issue by jackquack** [Aluxian/WhatsApp-Desktop#60]
I just started getting the "We recommend using WhatsApp Web with one of the following browsers:" screen on the client today. It was working this morning but now I can't get it to work.

My guess is that maybe they updated their server to recognize this client.
![screen shot 2015-09-09 at 2 00 18 pm](https://cloud.githubusercontent.com/assets/554881/9769978/655eff44-56fb-11e5-99c4-23d7bed728b3.png)

**Comment by phoenix-frozen** [comment]
Duplicate of #48 / #55

**Comment by jackquack** [comment]
Oh, sorry for the noise
