### ISSUE TITLE
Not working on Browser

### ISSUE THREAD

**Issue by computerjin** [Aluxian/WhatsApp-Desktop#61]
Hello,

Please can you check and rectify this issue.

Refused to display 'https://web.whatsapp.com/' in a frame because it set 'X-Frame-Options' to 'DENY'.
showing this error in console.

Regards,
Az

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
