### ISSUE TITLE
Use without keeping phone Connected

### ISSUE THREAD

**Issue by anil1692** [Aluxian/WhatsApp-Desktop#65]
I love the client. but if it worked without keeping phone connected than it could be more useful, Now messages between both Phone & Desktop clients can be synced whenever they are both online simultaneously. just let user log in first time s/he uses desktop client first time than he could use both clients whenever he wants but he ever uses both mobile and desktop clients simultaneously messages will sync. Is it possible?

**Comment by maxgomes92** [comment]
Acctually not.

**Comment by beppe9000** [comment]
It is a protocol limitation of the castrated version of XMPP Whatsapp is using.

**Comment by Aluxian** [comment]
@beppe9000 LOL 

@all give Whatsie a try:

https://github.com/Aluxian/Whatsie

Keeping your phone connected is still required, but pretty much everything else has been improved/fixed.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Comment by beppe9000** [comment]
What about using an android headless VM with Whatsapp installed?

**Comment by Aluxian** [comment]
That'd be the same thing as running something like bluestacks yourself, unless I designed a custom interface in front of the vm. But this would require too much work and I don't have time, besides the fact that I don't really like the idea.

**Comment by beppe9000** [comment]
Well my idea was only to replace the smartphone with a lightweight android VM running in the background as a service and keeping using whatsapp-desktop/whatsie as a frontend with OS integration.

PS. bluestacks is death: i tried it once and it started requiring intalling useless apps & games in order to keep it working.

**Comment by Aluxian** [comment]
Ohh, yeah, so the user would still use WhatsApp Web. But they'd need to set up the VM signing in with a phone number... and then scan the QR code? I still think it's too complicated to be worth it.

**Comment by beppe9000** [comment]
You are right. I think that maybe a data backup with titanium backup or similar from an already configured phone could be easier. Btw do you know any VM that supports execution as a local service?

**Comment by Aluxian** [comment]
Easier, but still too cumbersome to be considered easy, in my opinion. I think people who are not power users would find it so.

I don't know any, sorry.
