### ISSUE TITLE
Not Working in Ubuntu

### ISSUE THREAD

**Issue by denzelwamburu** [Aluxian/WhatsApp-Desktop#66]
Nice stuff but after i downloaded, it worked but trying to use it for the second time itd giving recommendations of browser clients. Can't seem to work after that. 
![screenshot from 2015-10-10 18 57 57](https://cloud.githubusercontent.com/assets/6532631/10412057/8ebe2c94-6f82-11e5-84b0-131196afa54b.png)

**Comment by peterrus** [comment]
experiencing the same

**Comment by peterrus** [comment]
duplicate of #60

**Comment by denzelwamburu** [comment]
Great, sorry didn't see that, but its not really cool that after deleting
the Application Cache still regenerates it.
