### ISSUE TITLE
On available update, don't link non-debian users to a *.deb file

### ISSUE THREAD

**Issue by hashworks** [Aluxian/WhatsApp-Desktop#68]
Non-Debian users should be send to https://github.com/Aluxian/WhatsApp-Desktop instead.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
