### ISSUE TITLE
Add HiDPI support

### ISSUE THREAD

**Issue by hashworks** [Aluxian/WhatsApp-Desktop#69]
Currently everything is really small on high resolution displays (f.e. 3200x1800) since it doesn't respect the DPI setting in xorg.conf. Chromium f.e. is working fine.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
