### ISSUE TITLE
Is it blocked?

### ISSUE THREAD

**Issue by nardev** [Aluxian/WhatsApp-Desktop#70]
I installed it on Debian but when i start the app, i get the message:

WhatsApp Web
Send and receive WhatsApp messages right from your computer.
We recommend using WhatsApp Web with one of the following browsers:
Google Chrome
Mozilla Firefox
Opera
WhatsApp Web also supports:
Safari (MacOS 10.8+ Only)

i'm i doing something wrong?

**Comment by decentaur** [comment]
Bug / fix is already reported as bug #52 (and that refers to other bugs as well)

**Comment by nardev** [comment]
thnx

**Comment by zweicoder** [comment]
@nardev You can try gutierri's fork or [mine](https://github.com/zweicoder/WhatsApp-Desktop)

**Comment by nardev** [comment]
@zweicoder  thnx

**Comment by Aluxian** [comment]
Hey, all, give Whatsie a try:

https://github.com/Aluxian/Whatsie

I fixed the issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
