### ISSUE TITLE
Please stop being a coward

### ISSUE THREAD

**Issue by sbourdeauducq** [Aluxian/WhatsApp-Desktop#71]
And reverse engineer that damn protocol. What are you afraid of?

**Comment by Rhedox** [comment]
That would be pointless. Whatsapp would just shut it down and his efforts would be wasted.
Just like countless other projects: https://raw.githubusercontent.com/github/dmca/master/2014-02-12-WhatsApp.md

**Comment by sbourdeauducq** [comment]
Well, screw DMCA, and take the project somewhere else. Do you need another git host?

**Comment by sbourdeauducq** [comment]
Many countries do not have such an imbecilic piece of legislation in place.

**Comment by hashworks** [comment]
Because everyone is happy to spend time and money consulting a lawyer.

**Comment by sbourdeauducq** [comment]
@Rhedox some of those projects you point to are still online on github and functional. Great!

**Comment by sbourdeauducq** [comment]
@hashworks get a life please.

**Comment by hashworks** [comment]
Really, go on. Fire up some books & search engines, reverse engineer the protocol and host it somewhere public. You'll see that Facebook will contact you quite soon. And then I want to see you not giving a fuck about it.
