### ISSUE TITLE
Desktop Pinning Issue

### ISSUE THREAD

**Issue by 4ni1** [Aluxian/WhatsApp-Desktop#72]
When this app is pinned to the desktop it creates a running instance of it next to it. 
![whatsapp](https://cloud.githubusercontent.com/assets/321785/10720778/46843b94-7b71-11e5-9f27-dcc45ef4c689.PNG)

**Comment by LucaScorpion** [comment]
Have you tried unpinning the first, and pinning the second (running) icon? Sometimes other apps to that for me too, and this usually fixes it.

**Comment by 4ni1** [comment]
Thank you @LucaScorpion. Closing the issue.
