### ISSUE TITLE
Constant CPU usage when idle

### ISSUE THREAD

**Issue by mstanescu** [Aluxian/WhatsApp-Desktop#73]
Hi,

Why is the app constantly eating 3% CPU even if its not in foreground or is minimized ? 
I see the same problem with Messenger app even though i did not even sign in.

Mihai

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie uses fewer resources, close to 0 when idle. 

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
