### ISSUE TITLE
Bug: cannot pass whatsapp's browser check

### ISSUE THREAD

**Issue by ax4** [Aluxian/WhatsApp-Desktop#79]
WhatsApp web client restrict to Chrome, Opera, Firefox, and Safari. So when I open the unofficial whatsapp client, it appears as the following picture.
![image](https://cloud.githubusercontent.com/assets/8946060/11927959/630b8b8a-a78d-11e5-8fb7-9073b75b3db8.png)

I checked nw.js project. It said "NW.js is an app runtime based on Chromium and node.js". But now it doesn't pass the whatsapp browser check for some reason. I don't know why.

**Comment by ax4** [comment]
Oh I found issues already exist at #74. Pleas ignore my duplicating.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
