### ISSUE TITLE
Increase/Decrease text size, etc.

### ISSUE THREAD

**Issue by YNedderhoff** [Aluxian/WhatsApp-Desktop#8]
Maybe one could add the possibilty to increase/decrease the possibility to change the size of everything (just like STRG++ or STRG+- in the browser)

**Comment by Aluxian** [comment]
It's on the to-do list :)

**Comment by boesing** [comment]
As additional feature you should add HiDPI functionality. I am on an XPS 13 2015 with 15.04 Ubuntu on it. Thanks in advance.

**Comment by Aluxian** [comment]
Working on it! :) I'm porting the app to Electron, most probably this will fix the issue.

**Comment by boesing** [comment]
Amazing, you rock.

**Comment by YNedderhoff** [comment]
Anything on that?

**Comment by boesing** [comment]
This project is dead.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

I've added this feature there.
