### ISSUE TITLE
More than one instance!

### ISSUE THREAD

**Issue by MDTomate** [Aluxian/WhatsApp-Desktop#80]
I have the fixed application on the taskbar. When I close the application, minimizing it to the tray, and click on the application icon in the Start Menu or the taskbar, instead of picking up the application open in the tray, it creates a new instance of the application, duplicating it. Some certainty of how to solve this?

**Comment by garenyondem** [comment]
:+1:

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
