### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by Tuning-Soft** [Aluxian/WhatsApp-Desktop#81]
![2016-01-11_13 42 05](https://cloud.githubusercontent.com/assets/1108013/12228698/6d89c13e-b869-11e5-9eaa-781498561408.png)

**Comment by kursion** [comment]
False positive ? I doubt that it's a malware from the source code.

**Comment by e-M-c-E** [comment]
Yeap.. false Positive and also crappy antivirus software ;)

**Comment by Tuning-Soft** [comment]
`Yeap.. false Positive and also crappy antivirus software ;)`
and what good antivirus software?)

**Comment by e-M-c-E** [comment]
@Tuning-Soft hmm.. I use kaspersky. This 360 thing is known from having adware. Something like those apps from Cheetah Mobile. Fast identical stuff. Ads, ads, ads, other bullshit and nothing more. ;)

**Comment by Tuning-Soft** [comment]
@e-M-c-E 
If i use 360 TS - crappy antivirus software ;)
If you use kaspersky - good antivirus software  ;)

excellent comparison!

May be kaspersky - crappy antivirus software?  ;)

Do you know, that everyone praises his pimped?) 
For me kaspersky - crappy antivirus software ;)

**Comment by e-M-c-E** [comment]
@Tuning-Soft sorry, but KIS don't have any ads, bloatware and other strange code inside. He just works as it should work. Especially v.4.9.x. And he don't give me any false positives since 2-3 yesrs.

**Comment by AdrianoCahete** [comment]
It's false positive for sure. That software is just an Electron (Chromium browser) calling a web whatsapp.
