### ISSUE TITLE
Can't listen to vocal messages

### ISSUE THREAD

**Issue by pietrochico** [Aluxian/WhatsApp-Desktop#82]
Am I the only one who can't listen to vocal messages sent by friends? 
I can see downloading bar working on it but no way to listen to any vocal messages.

Linux Mint 17, 64bit.

**Comment by sigrokBlack** [comment]
The same here(Linux)

**Comment by Rodrigowbs** [comment]
Here too

**Comment by flandolfi** [comment]
Same here (Ubuntu 15.10), but the problem seems to be extended to all application's sounds (as far as I know, there are no sound notifications too).

**Comment by nstamm** [comment]
Hi, same problem here on Linux Mint 17.2 64bit.

**Comment by flandolfi** [comment]
I think this project is migrating to [Whatsie](https://github.com/Aluxian/Whatsie). Vocal messages & sound notifications work fine with that one!

**Comment by Aluxian** [comment]
Hey, all, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
