### ISSUE TITLE
OSX version stopped working after 10.11.3 update

### ISSUE THREAD

**Issue by drake0101** [Aluxian/WhatsApp-Desktop#84]
Hi,
My UnofficialWhatsApp stopper working after upgrading OSX to 10.11.3.
Screenshot: [https://www.dropbox.com/s/di28uhwwjowtubv/Zrzut%20ekranu%202016-01-28%2011.52.04.png?dl=0](url)

**Comment by Aluxian** [comment]
Hey, can you please give Whatsie a try?

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
