### ISSUE TITLE
Facing some issues

### ISSUE THREAD

**Issue by rajeevrrs** [Aluxian/WhatsApp-Desktop#88]
Hello i am facing some issues 

1. It recommending me to use another browser 
2. I a scanning with QR code but my whatsapp is not opening 
3. Uninstall is missing 

I am using windows 8.1.

**Comment by Aluxian** [comment]
Hey, can you please give Whatsie a try?

https://github.com/Aluxian/Whatsie

1. Fixed
2. Fixed
3. Added

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
