### ISSUE TITLE
Doesn't whatsapp blocks users permanently who use it's unofficial app?

### ISSUE THREAD

**Issue by Faiz7412** [Aluxian/WhatsApp-Desktop#9]
I tried using yowsup to send whatsapp message from terminal. A week ago I was trying to integrate whatsapp plugin for pidgin. And while doing that, I came across this issue. https://github.com/davidgfnet/whatsapp-purple/issues/275
Whatsapp started blocking users since a month ago.

**Comment by Aluxian** [comment]
I'm aware of their practice. My app is unofficial, but it's just a wrapper around https://web.whatsapp.com/. So I'm not using their service/API directly.

**Comment by Aluxian** [comment]
I'm not 100% sure, but I strongly think they won't start banning. They can't. As I said, users still use web.whatsapp.com, just that not from a regular browser.

**Comment by Faiz7412** [comment]
I see. I opened that issue before using your app. I thought you were using the same theme as web.whatsapp.com and that it was a full-fledged client with all the options like changing your profile picture, updating status, etc. 
Have you tested it if it displays a person online all the time if they have the app running in the background?

**Comment by Aluxian** [comment]
I haven't tested. Please let me know if you do.

My thoughts are, that web.whatsapp.com detects when the user switches the tab and knows that they're idle. It should be able to detect when the WhatsApp for Desktop window is not focused too. However, I don't know WhatsApp Web's behaviour in such state.

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
