### ISSUE TITLE
Project seems to be dead :( Is it dead?

### ISSUE THREAD

**Issue by Nidre** [Aluxian/WhatsApp-Desktop#90]

**Comment by sigrokBlack** [comment]
Some people cloned it but the original is no longer supported I guess.

**Comment by Nidre** [comment]
@sigrokBlack Do you know any of that is stable?

**Comment by sigrokBlack** [comment]
No, I' m using the official without any issue.

**Comment by flandolfi** [comment]
I think this project is migrating to https://github.com/Aluxian/Whatsie

**Comment by Nidre** [comment]
@flandolfi Cool!
