### ISSUE TITLE
Audio recordings don't play

### ISSUE THREAD

**Issue by mrmayfield** [Aluxian/WhatsApp-Desktop#91]
I can correctly record an audio recording, and play my own audio recording, but I can't play audio recordings sent by others, I click the button but nothing happens although I can verify the recordings work with the web app.

**Comment by Aluxian** [comment]
Hey, can you please give Whatsie a try?

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
