### ISSUE TITLE
Cannot login after restarting the app 

### ISSUE THREAD

**Issue by dbogdanov** [Aluxian/WhatsApp-Desktop#92]
This is how it looks like know. How can I get back to my contacts window?

![bad](https://cloud.githubusercontent.com/assets/409668/13503511/0ee6e05a-e170-11e5-8982-9d020c9871d4.png)

**Comment by Emptaze** [comment]
This is already reported. https://github.com/Aluxian/WhatsApp-Desktop/issues/74

**Comment by julestruong** [comment]
not getting this app if this is not fixed ..

**Comment by strebl** [comment]
To delete the cache on Mac OS X:
```bash
rm -rf ~/Library/Application\ Support/UnofficialWhatsApp/Application\ Cache/*
```

**Comment by AdrianoCahete** [comment]
> not getting this app if this is not fixed ..

So will have to find another app. .. This bug is old.

**Comment by julestruong** [comment]
Yeah still using chrome

**Comment by CytoDev** [comment]
@dbogdanov, @Emptaze, @julestruong, @strebl, @AdrianoCahete: You can easily fix this issue by locking the `Application Cache` directory (`~/.config/UnofficialWhatsApp/Application\ Cache` on Linux). When this directory is not readable or writeable you can close the client as much as you like and return to your chats when opening it again. Why this issue persists is beyond me, but this is a fix.

**Comment by eliasjnior** [comment]
Would be possible to add some script to empty this cache folder on startup? It would fix the problem, I think.

**Comment by skruven80** [comment]
You may also write protect the entire folder and files in Windows:
\Users\Username\AppData\Local\UnofficialWhatsApp\Application Cache

**Comment by robertopierpaoli** [comment]
One time 'chmod 000 ~/.config/UnofficialWhatsApp/Application\ Cache' seems to be enough to get it working regularily.

**Comment by CytoDev** [comment]
@robertopierpaoli, it might be wise to authenticate with the servers of WhatsApp first. To be on the safe side with correct configuration.

**Comment by Aluxian** [comment]
Hey, everyone, please give Whatsie a try. I've fixed this issue there :)

https://github.com/Aluxian/Whatsie
