### ISSUE TITLE
hope telegram on the plan

### ISSUE THREAD

**Issue by wanjochan** [Aluxian/WhatsApp-Desktop#95]
Dear Aluxian, it is so great that you build wonderful app for messenger and whatsapp desktop with NWJS !  Really hope telegram might be on your plan also!  Or at least please open a new repository and call volunteers ;)

**Comment by Aluxian** [comment]
Hey @wanjochan, I do plan to do a Telegram app. However, given that Telegram already has some pretty good, cross-platform, native clients, what are some features you'd like to see?
