### ISSUE TITLE
client stopped working :(

### ISSUE THREAD

**Issue by manuel-delverme** [Aluxian/WhatsApp-Desktop#96]
WhatsApp Web
Send and receive WhatsApp messages right from your computer.
We recommend using WhatsApp Web with one of the following browsers:
![screenshot](https://cloud.githubusercontent.com/assets/1309922/14246594/80f74336-fa68-11e5-9f82-90bdd113d63e.png)

**Comment by datosh** [comment]
Just look at all at the [closed issues...](https://github.com/Aluxian/WhatsApp-Desktop/issues/92)

**Comment by julestruong** [comment]
@datosh i don't think this is how it works. If it is closed, It should not be seen. It means it is fixed somehow. The issue is still and nothing is done, its ok to create a new issue

**Comment by Aluxian** [comment]
@julestruong you're right about the issues thing, I closed them just to clear the repo. The fix to those issues is the new app. WAFD will be deprecated once Whatsie is released out of beta (15 April). All WhatsApp for Desktop users will be asked to upgrade to Whatsie.

@manuel-delverme I'm sorry for the confusion. WhatsApp for Desktop is now Whatsie, and you can get the beta from here:

https://github.com/Aluxian/Whatsie
