### ISSUE TITLE
Icon in title bar missing - Windows

### ISSUE THREAD

**Issue by diavolodeejay** [Aluxian/WhatsApp-Desktop#97]
In my title bar there isn't any icon :cry: 
[Here is a screeenshot](https://cloud.githubusercontent.com/assets/5551861/14257435/1064e7b4-fa9e-11e5-9c1c-b3ef050b3246.png)

I'm using windows 10 64bit

**Comment by Aluxian** [comment]
Hey, give Whatsie a try:

https://github.com/Aluxian/Whatsie

If the problem is still present, please open another issue there.

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.
