### ISSUE TITLE
the app doesn't start

### ISSUE THREAD

**Issue by Arvacon** [Aluxian/WhatsApp-Desktop#98]
I installed the program and it worked well the first time, but when I quit and reopen it, it shows that I must use the web application and can't open.
What am I doing wrong? Is this a bug?

![2016-04-09_2344](https://cloud.githubusercontent.com/assets/2128761/14406312/171ed372-fead-11e5-9b34-21b2ec73c289.png)

**Comment by dionysosz** [comment]
Same situation here with Ubuntu 15.10 64-bit. Is there any solution?

**Comment by geertw** [comment]
Worked for me after setting up, but the next time I opened I got this screen. Maybe whatsapp checks the user agent?

**Comment by chrootLogin** [comment]
Have the same problem... First Login works, but after restarting the app it won't. Same on Ubuntu 15.10 and OS X 10.11...

**Comment by Aluxian** [comment]
Hey, please switch to Whatsie:

https://github.com/Aluxian/Whatsie

Whatsie is, basically, WhatsApp for Desktop v2. It's in beta right now, while I still fix issues and add features, but it'll be released soon.

**Comment by chrootLogin** [comment]
Can you please add a notice in the readme.md? It would be very helpful.

**Comment by chrootLogin** [comment]
Can you please add a notice in the readme.md? It would be very helpful.

**Comment by Aluxian** [comment]
I will once Whatsie is fully released.

**Comment by raindev** [comment]
Given that Whatsie is functional and WhatsApp Desktop is not, I would still mention Whatsie in the readme with the appropriate disclaimer about work in progress.
